# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

'''PyQt5 file for GUI not implemented'''

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Battle(object):
    def setupUi(self, Battle):
        Battle.setObjectName("Battle")
        Battle.resize(326, 287)
        self.centralwidget = QtWidgets.QWidget(Battle)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_middle = QtWidgets.QFrame(self.centralwidget)
        self.frame_middle.setGeometry(QtCore.QRect(20, 10, 261, 161))
        self.frame_middle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_middle.setObjectName("frame_middle")
        self.radioButton_attack = QtWidgets.QRadioButton(self.frame_middle)
        self.radioButton_attack.setGeometry(QtCore.QRect(20, 60, 131, 30))
        self.radioButton_attack.setObjectName("radioButton_attack")
        self.radioButton_waltz = QtWidgets.QRadioButton(self.frame_middle)
        self.radioButton_waltz.setGeometry(QtCore.QRect(20, 110, 131, 30))
        self.radioButton_waltz.setObjectName("radioButton_waltz")
        self.radioButton_rhapsody = QtWidgets.QRadioButton(self.frame_middle)
        self.radioButton_rhapsody.setGeometry(QtCore.QRect(140, 60, 131, 30))
        self.radioButton_rhapsody.setObjectName("radioButton_rhapsody")
        self.radioButton_ballad = QtWidgets.QRadioButton(self.frame_middle)
        self.radioButton_ballad.setGeometry(QtCore.QRect(140, 110, 131, 30))
        self.radioButton_ballad.setObjectName("radioButton_ballad")
        self.label_actions = QtWidgets.QLabel(self.frame_middle)
        self.label_actions.setGeometry(QtCore.QRect(80, 10, 90, 26))
        self.label_actions.setObjectName("label_actions")
        self.pushButton_go = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_go.setGeometry(QtCore.QRect(90, 200, 114, 34))
        self.pushButton_go.setAutoFillBackground(False)
        self.pushButton_go.setObjectName("pushButton_go")
        Battle.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Battle)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 326, 22))
        self.menubar.setObjectName("menubar")
        Battle.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Battle)
        self.statusbar.setObjectName("statusbar")
        Battle.setStatusBar(self.statusbar)

        self.retranslateUi(Battle)
        QtCore.QMetaObject.connectSlotsByName(Battle)

    def retranslateUi(self, Battle):
        _translate = QtCore.QCoreApplication.translate
        Battle.setWindowTitle(_translate("Battle", "MainWindow"))
        self.radioButton_attack.setText(_translate("Battle", "Attack"))
        self.radioButton_waltz.setText(_translate("Battle", "Waltz"))
        self.radioButton_rhapsody.setText(_translate("Battle", "Rhapsody"))
        self.radioButton_ballad.setText(_translate("Battle", "Ballad"))
        self.label_actions.setText(_translate("Battle", "Actions:"))
        self.pushButton_go.setText(_translate("Battle", "Go!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Battle = QtWidgets.QMainWindow()
    ui = Ui_Battle()
    ui.setupUi(Battle)
    Battle.show()
    sys.exit(app.exec_())
